### ISSUE TITLE
TF2 with GPU support

### ISSUE THREAD

**Issue by 9nut** [wamuir/golang-tf#1]
It would be great to have the Dockerfiles for TF 2.4.1 with GPU support.

**Comment by wamuir** [comment]
@9nut can you please test?

I've also pushed to docker hub [`wamuir/golang-tf:2.4.1-gpu`](https://hub.docker.com/layers/wamuir/golang-tf/2.4.1-gpu/images/sha256-e51882c12a22e526fedc148ef69623cdc4cc47fbbb504648e2576fa6604a3b02?context).  If you haven't done so already, you'll need to install the [NVIDIA Container Toolkit](https://github.com/NVIDIA/nvidia-docker) to expose the GPU within Docker (use the `--gpus all` flag).
